import random
import sys
import time
def mengetik(s):
    for c in s + '\n':
        sys.stdout.write(c)
        sys.stdout.flush()
        time.sleep(random.random() * 0.2)
mengetik('Loading.................')
mengetik('Mohon Tunggu............')
mengetik('........................')
mengetik('........................')
mengetik('........................')
mengetik('........................')
mengetik('........................')
mengetik('........................')
mengetik('........................')
mengetik('........................')
mengetik('........................')
mengetik('........................')
mengetik('Meminta Akses Login.....')
mengetik('........................')
mengetik('........................')
mengetik('........................')
mengetik('Meminta Akses Success...')
mengetik('+--------------------------+')
mengetik('+--------------------------+')
mengetik('SYSTEM PROGRAM ACTIVE')
mengetik('+--------------------------+')
mengetik('+--------------------------+')
mengetik('+--------------------------+')
mengetik('Hi namaku Dugen')
mengetik('+--------------------------+')
mengetik('Ducakpil Generator')
mengetik('+--------------------------+')
mengetik('Saya Diciptakan Oleh Tuan Fauzi...')
mengetik('Saya Diciptakan Untuk Mencari Informasi...')
mengetik('Saya Diciptakan Untuk Menjadi Database...')
mengetik('Penduduk Indonesia...')
mengetik('+--------------------------+')
mengetik('Semoga Kamu Suka... ^_^')
mengetik('+--------------------------+')
mengetik('+--------------------------+')
