import random
import sys
import time
def mengetik(s):
    for c in s + '\n':
        sys.stdout.write(c)
        sys.stdout.flush()
        time.sleep(random.random() * 0.2)
mengetik('INFORMASI KK DAN NIK')
mengetik('                    ')
mengetik('DUCAKPIL = SURABAYA')
mengetik('                   ')
mengetik('NAMA : MOCHAMMAD HUDA AR-RAYYAN')
mengetik('ALAMAT : PETUKANGAN TENGAH 18F')
mengetik('NIK : 3578162301200001 ')
mengetik('KK  : 3578160706100026 ')
mengetik('                       ')
mengetik('NAMA : MUHAMMAD ALI ZAINAL ABIDIN')
mengetik('ALAMAT : PETUKANGAN TENGAH 18C')
mengetik('NIK : 3578162204180002')
mengetik('KK  : 3578161202180021')
mengetik('                       ')
mengetik('NAMA : BADRAH')
mengetik('ALAMAT : PETUKANGAN TENGAH 20E')
mengetik('NIK : 3578163006300025')
mengetik('KK  : 3578160301089374')
mengetik('                       ')
mengetik('NAMA : ALI')
mengetik('ALAMAT : PETUKANGAN TENGAH 28')
mengetik('NIK : 3527061702720004')
mengetik('KK  : 3578160107130003')
mengetik('                       ')
mengetik('NAMA : DWI SINAR ANJALY')
mengetik('ALAMAT : PETUKANGAN TENGAH 28')
mengetik('NIK : 3578162102150001')
mengetik('KK  : 3578160403170007')
mengetik('                       ')
mengetik('NAMA : ABI ARIF MAULANA')
mengetik('ALAMAT : PETUKANGAN TENGAH 28C')
mengetik('NIK : 3578130502140001')
mengetik('KK  : 3578160202190001')
mengetik('                       ')
mengetik('NAMA : HAMID')
mengetik('ALAMAT : PETUKANGAN TENGAH 28C')
mengetik('NIK : 3578160802590004')
mengetik('KK  : 3578162605110018')
mengetik('                       ')
mengetik('NAMA : SITI HADIYAH')
mengetik('ALAMAT : PETUKANGAN TENGAH 28I')
mengetik('NIK : 3578166401670001')
mengetik('KK  : 3578160711170010')
mengetik('                       ')
mengetik('NAMA : MOCH SUBHAN')
mengetik('ALAMAT : PETUKANGAN TENGAH 30')
mengetik('NIK : 3578161605750008')
mengetik('KK  : 3578160201083220')
mengetik('                       ')
mengetik('NAMA : SAMSUL ARIFIN')
mengetik('ALAMAT : PETUKANGAN TENGAH 30')
mengetik('NIK : 3578160204750005')
mengetik('KK  : 3578160201088149')
mengetik('                       ')
mengetik('NAMA : ZAINAB ALAYDRUS')
mengetik('ALAMAT : PETUKANGAN TENGAH 30')
mengetik('NIK : 3578124903650002')
mengetik('KK  : 3578120703130008')
mengetik('                       ')
mengetik('NAMA : ABDUL MALIK')
mengetik('ALAMAT : PETUKANGAN TENGAH 30')
mengetik('NIK : 3578163006760015')
mengetik('KK  : 3578161504110023')
mengetik('                       ')
mengetik('NAMA : ACH MARSUKI')
mengetik('ALAMAT : PETUKANGAN TENGAH 30')
mengetik('NIK : 3578162408670007')
mengetik('KK  : 3578161509160006')
mengetik('                       ')
mengetik('NAMA : M.ALI IBRAHIM')
mengetik('ALAMAT : PETUKANGAN TENGAH 30')
mengetik('NIK : 3578160508810006')
mengetik('KK  : 3578161805110062')
mengetik('                       ')
mengetik('NAMA : MOHAMMAD')
mengetik('ALAMAT : PETUKANGAN TENGAH 30')
mengetik('NIK : 3578122810880001')
mengetik('KK  : 3578161912190026')
mengetik('                       ')
mengetik('NAMA : USMAN')
mengetik('ALAMAT : PETUKANGAN TENGAH 30-32')
mengetik('NIK : 3578122606740001')
mengetik('KK  : 3578160201081207')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')
mengetik('                       ')
mengetik('NAMA : ')
mengetik('ALAMAT : ')
mengetik('NIK : ')
mengetik('KK  : ')

